#!/usr/bin/env bash
# Update package repositories and install nginx
sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html
service nginx start
